version: "3.1"
services:
  mongo:
    container_name: mongodb_container
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pwd123
    volumes:
      - mongodb-vol:/data/db
      - ./initdb:/docker-entrypoint-initdb.d  
    networks:
      - mongodb-net

  mongo-express:
    container_name: mongo-express_container
    image: mongo-express
    restart: always
    ports:
      - 8801:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd123
      ME_CONFIG_MONGODB_URL: mongodb://root:pwd123@mongodb_container:27017/
    networks:
      - mongodb-net

volumes:
    mongodb-vol:
     driver: local

networks:
    mongodb-net:
     driver: bridge